services:
  nginx:
    build: nginx
    volumes:
      - ./nginx/php.conf:/etc/nginx/conf.d/php.conf
      - ./nginx/python.conf:/etc/nginx/conf.d/python.conf
      - ./nginx/java.conf:/etc/nginx/conf.d/java.conf
    ports:
      - 80:80
      - 90:90
      - 100:100

  php:
    build: php
    working_dir: /var/www/html
    volumes:
      - ./php:/var/www/html

  python:
    build: python
    working_dir: /application
    volumes:
      - ./python:/application

  java:
    build: java
    working_dir: /application
    volumes:
      - ./java:/application